=== martinmolema/L-System/json-schema-definitions/lsystem-definition-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://molema.org/math-lsystem",
  "title": "L-system definitions",
  "description": "A list of L-System Definitions",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "systemName": {
        "type": "string",
        "description": "The unique name of the system"
      },
      "variables": {
        "type": "array",
        "description": "all the variables in the formula so we can determine which variables will actually draw lines",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "varname": {
            "type": "string"
          },
          "isDrawingVariable": {
            "type": "boolean"
          }
        }
      },
      "rules": {
        "type": "array",
        "uniqueItems": true,
        "minItems": 1,
        "items": {
          "type": "string",
          "description": "The formulas governing the L-System"
        }
      },
      "axiom": {
        "type": "string",
        "description": "The first set of chars to be parsed"
      },
      "rotationAngle": {
        "type": "number",
        "default": 45,
        "description": ""
      },
      "startingAngle": {
        "type": "number",
        "default": 90,
        "description": ""
      },
      "lineLength": {
        "type": "number",
        "default": 10,
        "description": ""
      },
      "lineLengthMultiplier": {
        "type": "number",
        "default": 1,
        "description": ""
      },
      "strokeColor": {
        "type": "string",
        "default": "black",
        "description": "The color used when to draw lines"
      },
      "fadeStrokeOpacity": {
        "enum": [
          "None",
          "Normal",
          "Reverse"
        ],
        "default": "None",
        "description": "Whether to make the lines fade with higher iterations"
      },
      "originPosition": {
        "type": "integer",
        "minimum": 0,
        "maximum": 10,
        "default": 1,
        "description": "The type of origin e.g. Center, TopLeft, etc. This is an numeric enum!"
      },
      "originCoordinates": {
        "type": "object",
        "description": "If the originPosition is value zero (0), then a set of coordinates must be specified, relative to the canvas' origin (0,0). Notice that the Y-axis positive value go from bottom to top!",
        "properties": {
          "x": {
            "type": "number",
            "default": 0
          },
          "y": {
            "type": "number",
            "default": 0
          }
        }
      }

    },
    "required": ["systemName","rules","variables","axiom","rotationAngle","lineLength"]
  }
}

=== martinmolema/L-System/src/assets/definitions.json
[
  {
    "systemName": "bushy cactus tree",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      },
      {
        "varname": "Y",
        "isDrawingVariable": false
      }
    ],
    "axiom": "Y",
    "rules": [
      "X=X[-FFF][+FFF]FX",
      "Y=YFX[+Y][-Y]"
    ],
    "rotationAngle": 25.7,
    "startingAngle": 90,
    "lineLength": 5,
    "lineLengthMultiplier": 1,
    "originPosition": 9,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "squares",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      }
    ],
    "axiom": "F+F+F+F",
    "rules": [
      "F=FF+F-F+F+FF"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 20,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Fractal tree",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      }
    ],
    "axiom": "FX",
    "rules": [
      "X= >[-FX]+FX"
    ],
    "rotationAngle": 40,
    "startingAngle": 90,
    "lineLength": 200,
    "lineLengthMultiplier": 0.5,
    "originPosition": 9,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "plant left oriented",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      }
    ],
    "axiom": "X",
    "rules": [
      "X=F-[[X]+X]+F[+FX]-X",
      "F=FF"
    ],
    "rotationAngle": 22.5,
    "startingAngle": 90,
    "lineLength": 5,
    "lineLengthMultiplier": 1,
    "originPosition": 9,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "square sierpinski",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      }
    ],
    "axiom": "F+XF+F+XF",
    "rules": [
      "X=XF-F+F-XF+F+XF-F+F-X"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 10,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "??",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      }
    ],
    "axiom": "F+F+F+F",
    "rules": [
      "F=F+F-F-FF+F+F-F"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 5,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "triangles",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      }
    ],
    "axiom": "F+F+F",
    "rules": [
      "F=F-F+F"
    ],
    "rotationAngle": 120,
    "startingAngle": 90,
    "lineLength": 20,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Peano Curve",
    "variables": [
      {
        "varname": "X",
        "isDrawingVariable": false
      },
      {
        "varname": "Y",
        "isDrawingVariable": false
      },
      {
        "varname": "F",
        "isDrawingVariable": false
      }
    ],
    "axiom": "X",
    "rules": [
      "X=XFYFX+F+YFXFY-F-XFYFX",
      "Y=YFXFY-F-XFYFX+F+YFXFY"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 5,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Sierpinski Arrowhead",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      },
      {
        "varname": "Y",
        "isDrawingVariable": false
      }
    ],
    "axiom": "YF",
    "rules": [
      "X=YF+XF+Y",
      "Y=XF-YF-X"
    ],
    "rotationAngle": 60,
    "startingAngle": 0,
    "lineLength": 10,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Hilbert curve",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      },
      {
        "varname": "Y",
        "isDrawingVariable": false
      }
    ],
    "axiom": "X",
    "rules": [
      "X=-YF+XFX+FY-",
      "Y=+XF-YFY-FX+"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 10,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Quadratic Snowflake variant B",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      }
    ],
    "axiom": "FF+FF+FF+FF",
    "rules": [
      "F=F+F-F-F+F"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 3,
    "lineLengthMultiplier": 1,
    "originPosition": 1,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "Quadratic Gosper",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "X",
        "isDrawingVariable": false
      },
      {
        "varname": "Y",
        "isDrawingVariable": false
      }
    ],
    "axiom": "-YF",
    "rules": [
      "X=XFX-YF-YF+FX+FX-YF-YFFX+YF+FXFXYF-FX+YF+FXFX+YF-FXYF-YF-FX+FX+YFYF-",
      "Y=+FXFX-YF-YF+FX+FXYF+FX-YFYF-FX-YF+FXYFYF-FX-YFFX+FX+YF-YF-FX+FX+YFY"
    ],
    "rotationAngle": 90,
    "startingAngle": 90,
    "lineLength": 5,
    "lineLengthMultiplier": 1,
    "originPosition": 4,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  },
  {
    "systemName": "L-system leaf",
    "variables": [
      {
        "varname": "F",
        "isDrawingVariable": true
      },
      {
        "varname": "x",
        "isDrawingVariable": false
      },
      {
        "varname": "y",
        "isDrawingVariable": false
      },
      {
        "varname": "a",
        "isDrawingVariable": false
      },
      {
        "varname": "b",
        "isDrawingVariable": false
      }
    ],
    "axiom": "a",
    "rules": [
      "F=>F<",
      "a=F[+x]Fb",
      "b=F[-y]Fa",
      "x=a",
      "y=b"
    ],
    "rotationAngle": 30,
    "startingAngle": 90,
    "lineLength": 10,
    "lineLengthMultiplier": 0.5,
    "originPosition": 9,
    "originCoordinates": {
      "iterationNr": -1,
      "letter": "",
      "x": 0,
      "y": 0
    }
  }
]
